import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <nav>
          <Link href='/'>HOME</Link>
          <Link href='/products'>PRODUCTS</Link>
          <Link href='/posts'>POSTS</Link>
          <Link href='/about'>ABOUT</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
