import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div id='app'>
          <header className='site-header'>
            <Link href='/' className='site-logo'>
              Shop
            </Link>
            <nav className='site-nav'>
              <Link href='/' className='nav-link'>
                Products
              </Link>
              <Link href='/cart' className='nav-link'>
                Cart
              </Link>
              <Link href='/admin/add' className='nav-link'>
                Add Product
              </Link>
            </nav>
          </header>
          <main id='main-content'>{children}</main>
        </div>
      </body>
    </html>
  );
}
